# Created on: Oct 29, 2012
#     Author: jorge
# Configuration for subscribers to cmd_vel sources. This file is provided just as an example.
# Typically automatic controllers, as ROS navigation stack should have the minimum priority
#
# Individual subscriber configuration:
#   name:           Source name
#   topic:          The topic that provides cmd_vel messages
#   timeout:        Time in seconds without incoming messages to consider this topic inactive
#   priority:       Priority: an UNIQUE unsigned integer from 0 (lowest) to MAX_INT
#   short_desc:     Short description (optional)

subscribers:
  - name:        "Navigation stack"
    topic:       "cmd_vel/nav"
    timeout:     0.5
    priority:    1
    short_desc:  "Navigation stack controller"
  - name:        "Onboard joystick"
    topic:       "cmd_vel/joy"
    timeout:     0.1
    priority:    6
  - name:        "Keyboard operation"
    topic:       "cmd_vel/keyop"
    timeout:     0.1
    priority:    7
  - name:        "Safety controller"
    topic:       "cmd_vel/safe"
    timeout:     0.5
    priority:    10
    short_desc:  "Safety controller"

publisher:       "cmd_vel/out"
